---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by LilithGames.
--- DateTime: 2021/7/9 10:45
---

module("system",package.seeall)

BaseDataStructure = Class("BaseDataStructure")

function BaseDataStructure:tor()
    self._dataList = {}--数据列表
    self._dataCount = 0--数据列表元素数量
end

--查找,1,仅判断是否包含
function BaseDataStructure:IsContains(data)
    if self._dataCount == 0 then
        return false
    end
    for i = self._dataCount, 1, -1 do
        if self._dataList[i] == data then  --递减
            return true
        end
    end
    return false
end

--查找2，取数据并移除
function BaseDataStructure:_getAndRemoveTop()
    if self._dataCount == 0 then
        return nil
    end
    local topIndex = self:_getTopIndex()
    local data = self._dataList[topIndex]
    table.remove(self._dataList, topIndex)
    self._dataCount = self._dataCount - 1
    return data
end

--添加数据
function BaseDataStructure:AddData(data)
    table.insert(_dataList,data)
    self._dataCount = self._dataCount+1
end

--移除数据：
function BaseDataStructure:RemoveData(data)
    if self._dataCount == 0 then
        return
    end
    for i = self._dataCount, -1,1 do
        if self._dataCount[i] == data then
            table.remove(_dataList,i)
            self._dataCount = self._dataCount-1
            break    --这里写return?
        end
    end
end



--新增加   修改数据
function BaseDataStructure:ChangeData(bdata,Adata)
    if self._dataCount == 0 then
        return
    end
    for i = self._dataCount, -1,1 do
        if self._dataCount[i] == bdata then
            self._dataCount[i] = Adata   --用table应该怎么写
            break    --这里写return?
        end
    end
end




--查看顶部的数据
function BaseDataStructure:_peekTop()
    if self._dataCount == 0 then
        return nil
    end
    return self._dataList[self:_getTopIndex()]
end

--取顶部的Index
function BaseDataStructure:_getTopIndex()
    LogError("需要子类覆写")
end

--获得距离顶部Count数量的Index
--1为顶部
function BaseDataStructure:_getDistanceTopIndex(count)
    LogError("需要子类覆写")
end

return BaseDataStructure






